import "./globals.css";
import Navbar from "@/app/Mainpage/Navbar";

export const metadata = {
  title: "Blog Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className='navbar'>
                <Navbar />
            </div>
        <div style={{position:'relative'}}>
          {children}
        </div>
      </body>
    </html>
  )
}